language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_deploy:
- npm run build
deploy:
  provider: lambda
  function_name: "dinnerBot"
  region: "eu-central-1"
  role: "arn:aws:iam::206421054703:role/travis_deploy"
  runtime: "nodejs6.10"
  handler_name: "handler"
