language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
before_script:
- npm run lint
after_success:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- bundle exec rspec
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
- npm run build
- cd dist
deploy:
  skip_cleanup: true
  provider: lambda
  function_name: "lunchable_bot"
  region: "eu-central-1"
  role: "arn:aws:iam::206421054703:role/travis_deploy"
  runtime: "nodejs6.10"
  handler_name: "handler"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: master
after_deploy:
  notifications:
    webhooks:
      urls:
      - $WEBHOOK_URL
      on_success: always
